language: python
python: ["3.6"]
install:
  - pip install -U pip setuptools tox
  - tox
  - git describe --tags > webdriver_recorder/VERSION
script:
  - /bin/true
deploy:
  skip_cleanup: true
  provider: script
  script: pip install twine && python setup.py sdist && twine upload dist/*
  on:
    tags: true
