language: python
python: ["3.6"]
addons:
  chrome: stable
install:
  - CHROMEDRIVER_DIR=/usr/local/bin CHROMEDRIVER_DIST=linux64 sudo ./bootstrap_chromedriver.sh
  - pip install -U pip setuptools tox
  - git describe --tags > webdriver_recorder/VERSION
script:
  - tox  # This runs tests, runs flake8, and generates a coverage report both in html and in the terminal.
deploy:
  skip_cleanup: true
  provider: script
  script: pip install twine && python setup.py sdist && twine upload dist/*
  on:
    tags: true
