language: python
python:
  - '3.6'
node_js: node
install:
  - git describe --tags > webdriver_recorder/VERSION
  - pip install -U pip setuptools
  - pip install python-coveralls coverage
  - npm install phantomjs-prebuilt
script:
  - coverage run --source=. --omit='.eggs/*' setup.py test
  - coveralls
before_deploy:
deploy:
  skip_cleanup: true
  provider: script
  script: pip install twine && python setup.py sdist && twine upload dist/*
  on:
    tags: true
