language: python
python:
  - '3.6'
node_js: node
install:
  - pip install -U pip setuptools
  - pip install python-coveralls coverage
  - npm install phantomjs-prebuilt
script:
  - coverage run --source=. --omit='.eggs/*' setup.py test
  - coveralls
deploy:
  provider: pypi
  user:
    secure: bT/XoqsIg6qfbeRRWXZOL4dhM2fWRFzYpCgnRAN4anN++NCAcrc400FCD2uFPn8tx//OJw6/lGA4BkocPm/VYifceMmJrs0ldAQ1kyrOAakDnrMwtKr2LqVVyGvXsXFDi8bBHDbuiNZw3BjIxGv6ktwC1XshPs2qhRfMiXWXq8xscuO8fIMDSPPuwWegdSAaRpjsOpTLxkMU2S0sudm2aIEakgu9kCHbqSiL9ysllgnKb5AtBeeJmOMQEs0XEWD78x2O6QcOf7vQoh82aVX+ZNvoraGS7tqKgRTtZPLiKYlPcYsy/pEpWzE9psZqhGMpNDUMMUXebD8WdyeYXh5CNZmdVqW0HnADU5ZE03g2cfjaYMLoe9tyPC4rVUWJB5sYECGEIcs0AkHE3kJJlANfmps7NNGqk94dnbmBdDxDDeljOMofqvPyz27c3E2fF9MYUrRjS5e7ywbvJgyJ1XzaUiWMzm08az0WTM4RYIEZHZhFq9iEbl1fGijSdWlNAuidHUJ9flTfpyxamOW7C0BVuzwuklb/OIzOa0R11jQe8LEj4MvML7qZnsoBH1WmUtvNCPIHzfbGXAEhwCI1mdLbtx/HQh2UGWG7qT9PixrQLLBpW9m0EToR1k9ptNd+tk61gkX28pNqDfhQ98VSUYfeDmL/55nInYL/PA/o9g1u62o=
  password:
    secure: q07PLUTDsUzCX1IWts8vb4HGBIljmv/taVeSPzQ9OjHbYkSiYAbRfYoZFjybFtuMrk02ThfWMaR2VvbV8veRFDXw8ZAt2ZuJ99XhyX0mDMmEsnX/LRayEY00oBtwxs1hxfgOd3e/8jlSlFsVntykphyWIahGVGx4TUY3ZDpEYTrQhvCIEGws0QxwrNDPY2cdwYQg0Td95shaXh/k7vcIPlbblHqY30a3bKCfvhiBvDtF+6h9QDyFpteoNdFyfvaUtKqXOlyeG+osFN9rkAoPTAQhDDhixdgbtSFKL5/mQ25rUmVUIY1H2lHYUgs0BqV0mZ/tQFxkFvHlkI4Ykg421czhCejK8Rq5q6f44rL0SiMa4fhIwLal9OPQ1xgoMH7g9CcaKcZfhbseU2sr4qUMa6AqrkXLpRWrxvscEWIjHP8YvC0gSM26uGW8YUwDdx42/xtYoW/nYRc/i7sNyc/rzx3LWU4LS4JpfI0Kxi9AVf0dgr2IUbYCuZEAt4uX1UQNwzlRKtFKWZZg7vu0jnr/QvYy/tdAVFEawybUInVM7x0iJphY17GdwfAZ+lfBkz04XRWHIkUIU1/4IZGRmOCFYK0EIXSMdaQKj8YJ4+p2ZD13P25pzVcpYh/yl9Ql0D3bu594EiNc1zPrLJa/iQYxMC08nGcXB/xiV4ElKn0cKvI=
  on:
    tags: true
