[tool.poetry]
name = "uw-webdriver-recorder"
# This version string is typically managed by the CI workflow,
# and is changed anytime `poetry version [new version]` is run.
# Do not revert this manually.
version = "5.0.2"
description = "A pytest plugin for recording screenshots of selenium interactions, with other convenient features too."
authors = ["Tom Thorogood <goodtom@uw.edu>"]
license = "Apache Software License 3.0"
classifiers = [
    "Framework :: Pytest",
    'License :: OSI Approved :: Apache Software License',
]
packages = [
    { include = "webdriver_recorder" }
]

[tool.poetry.plugins.pytest11]
"uw-webdriver-recorder" = "webdriver_recorder.plugin"

[tool.poetry.dependencies]
python = "^3.7"
pytest = "^6.2.4"  # NOT a dev dependency, as this is a plugin for pytest!
Jinja2 = "^3.0.1"
selenium = "^4.1.0"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
tox = "^3.23.1"
coverage = "^5.5"
pytest-coverage = "^0.0"
flake8 = "^3.9.2"
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = [
    "daily: marks tests that can only run once per day unless eval test data is reset.",
    "external: marks test that call an external endpoint. Deselect with '-m not external'"
]
