name: Build and validate plugin
on:
  pull_request:
  push:
    branches:
     - test-build-and-validate-workflow
     - main

jobs:
  validate:
    container:
      image: ghcr.io/uwit-iam/poetry:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: poetry install
      - run: tox
        id: tox
      - if: always()
        run: |
          if [[ -d "./webdriver-report" ]]
          then
              echo "::set-output name=upload-webdriver-report::true"
          fi
          if [[ -d "./htmlcov" ]]
          then
              echo "::set-output name=upload-coverage-report::true"
          fi
      - if: always() && steps.tox.outputs.upload-webdriver-report
        uses: actions/upload-artifact@v2
        with:
          name: web test storyboards for for ${{ github.sha }}
          path: ./webdriver-report/index.html
      - if: always() && steps.tox.outputs.upload-coverage-report
        uses: actions/upload-artifact@v2
        with:
          name: coverage report for ${{ github.sha }}
          path: ./htmlcov
